### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by GanYuhui** [vertopal/vertopal-php#1]
调用下载的接口为什么输出的内容最后有包含

ɋ��;'���oF295eda3c9dcb4fd0a3623e91411ae4df-04.jpgP8nWx��"�'��H295eda3c9dcb4fd0a3623e91411ae4df-02.jpgP8nW��
�)�'���2I295eda3c9dcb4fd0a3623e91411ae4df-25.jpgPK!!�
��K/Converted by Vertopal
https://www.vertopal.com/

我不知道是不是这个原因导致的，下载后始终无法打开

**Comment by vertonim** [comment]
This is the binary content of a ZIP archived file.

Vertopal automatically ZIP archives the output result of any file conversion that has produced multiple files. For instance, if you convert a multi-frame GIF file to JPG, the output file won't be JPG; instead, it will be a ZIP file containing multiple JPG files.

Use `Vertopal\API\Converter::download` and `Vertopal\API\V1::downloadFile` methods properly to avoid such a problem. For the former, don't pass any value as the `$filename` and your file will be saved as a ZIP file.

To ensure a more thorough review of your issue, kindly provide the code block you used.

And please, write in English. We don't speak Chinese.
